version: "3"

services:
    db:
      image: mysql:latest
      container_name: "MySQL_DB"
      command: --max_allowed_packet=1G
      ports:
        - "33006:3306"
      cap_add:
        - SYS_NICE
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mapsdb
