-- MySQL Script generated by MySQL Workbench
-- mån 11 jan 2021 21:10:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `ParentId` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `fk_category_category1_idx` (`ParentId` ASC) VISIBLE,
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`ParentId`)
    REFERENCES `mydb`.`category` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Hash` VARCHAR(255) NOT NULL,
  `Salt` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `DateOfBirth` DATE NULL,
  `JoinDate` DATE NOT NULL,
  `PermissionLevel` TINYINT(255) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`PhoneNumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Place` VARCHAR(45) NOT NULL,
  `Longitude` DECIMAL(6,3) NOT NULL,
  `Latitude` DECIMAL(5,3) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `UserId` INT NULL,
  `CategoryId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_location_user1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_location_category1_idx` (`CategoryId` ASC) VISIBLE,
  CONSTRAINT `fk_location_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`user` (`Id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_location_category1`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `mydb`.`category` (`Id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`badge` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Image` BLOB NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_badge` (
  `UserId` INT NOT NULL,
  `BadgeId` INT NOT NULL,
  `DateAcquired` DATE NOT NULL,
  PRIMARY KEY (`UserId`, `BadgeId`),
  INDEX `fk_user_has_badge_badge1_idx` (`BadgeId` ASC) VISIBLE,
  INDEX `fk_user_has_badge_user1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_badge_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`user` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_badge_badge1`
    FOREIGN KEY (`BadgeId`)
    REFERENCES `mydb`.`badge` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`picture` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ImageName` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `UserId` INT NOT NULL,
  `LocationId` INT NOT NULL,
  `FileName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_picture_user1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_picture_location1_idx` (`LocationId` ASC) VISIBLE,
  UNIQUE INDEX `FileName_UNIQUE` (`FileName` ASC) VISIBLE,
  CONSTRAINT `fk_picture_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`user` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_picture_location1`
    FOREIGN KEY (`LocationId`)
    REFERENCES `mydb`.`location` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`picture_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`picture_like` (
  `PictureId` INT NOT NULL,
  `UserId` INT NOT NULL,
  `Liked` TINYINT(1) NOT NULL,
  PRIMARY KEY (`PictureId`, `UserId`),
  INDEX `fk_picture_has_user_user1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_picture_has_user_picture1_idx` (`PictureId` ASC) VISIBLE,
  CONSTRAINT `fk_picture_has_user_picture1`
    FOREIGN KEY (`PictureId`)
    REFERENCES `mydb`.`picture` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_picture_has_user_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`user` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visited_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visited_location` (
  `LocationId` INT NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`LocationId`, `UserId`),
  INDEX `fk_location_has_user_user1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_location_has_user_location1_idx` (`LocationId` ASC) VISIBLE,
  CONSTRAINT `fk_location_has_user_location1`
    FOREIGN KEY (`LocationId`)
    REFERENCES `mydb`.`location` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_location_has_user_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`user` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `ReviewText` VARCHAR(1024) NOT NULL,
  `Score` DECIMAL(2,1) NOT NULL,
  `DateCreated` DATE NOT NULL,
  `UserId` INT NOT NULL,
  `LocationId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_review_user1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_review_location1_idx` (`LocationId` ASC) VISIBLE,
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`user` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_location1`
    FOREIGN KEY (`LocationId`)
    REFERENCES `mydb`.`location` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`review_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`review_like` (
  `ReviewId` INT NOT NULL,
  `UserId` INT NOT NULL,
  `Liked` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ReviewId`, `UserId`),
  INDEX `fk_review_has_user_user1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_review_has_user_review1_idx` (`ReviewId` ASC) VISIBLE,
  CONSTRAINT `fk_review_has_user_review1`
    FOREIGN KEY (`ReviewId`)
    REFERENCES `mydb`.`review` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_has_user_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`user` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CommentText` VARCHAR(255) NOT NULL,
  `ReviewId` INT NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_comment_review1_idx` (`ReviewId` ASC) VISIBLE,
  INDEX `fk_comment_user1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_comment_review1`
    FOREIGN KEY (`ReviewId`)
    REFERENCES `mydb`.`review` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`user` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment_like` (
  `UserId` INT NOT NULL,
  `CommentId` INT NOT NULL,
  `Liked` TINYINT(1) NOT NULL,
  PRIMARY KEY (`UserId`, `CommentId`),
  INDEX `fk_user_has_comment_comment1_idx` (`CommentId` ASC) VISIBLE,
  INDEX `fk_user_has_comment_user1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_comment_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`user` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_comment_comment1`
    FOREIGN KEY (`CommentId`)
    REFERENCES `mydb`.`comment` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rating` (
  `UserId` INT NOT NULL,
  `LocationId` INT NOT NULL,
  `Score` DECIMAL(2,1) NOT NULL,
  PRIMARY KEY (`UserId`, `LocationId`),
  INDEX `fk_user_has_location_location1_idx` (`LocationId` ASC) VISIBLE,
  INDEX `fk_user_has_location_user1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_location_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`user` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_location_location1`
    FOREIGN KEY (`LocationId`)
    REFERENCES `mydb`.`location` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
